In [1]:
import pandas as pd
import numpy as np

In [11]:
df1 = pd.read_csv('spotify-albums_data_2023.csv')
df1

,track_name,track_id,track_number,duration_ms,album_type,artists,total_tracks,album_name,release_date,label,...,artist_3,artist_4,artist_5,artist_6,artist_7,artist_8,artist_9,artist_10,artist_11,duration_sec
0,Amazing Grace,6mN8nzCXWUeT5LWEcG1Utx,5,555521,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,555.521
1,Silent Night,58sgjtx3FOnBBEOd3BQE6C,8,535041,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,535.041
2,Ancient Canyons,45tQJhm0WSk5VWMZK3FsLK,1,545855,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,545.855
3,Pacha Mama Medicina,3VFD7QqkJSg0OR6yBwKl7A,6,305241,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.241
4,Palace Of Light,7LwJV5BEIC9BQnzvaBSyCc,7,351060,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438968,Where She Goes,2sTDlCxmuZCTDKKk9f1qus,17,231704,album,NaN,22,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,231.704
438969,Europa :(,6vh4S1z08AjGipGAEsV62e,20,11904,album,NaN,22,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.904
438970,Seda,1YnChEM51BVZ5dRhbVFEMl,8,190476,album,NaN,22,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190.476
438971,Un Preview,5ixdmTpCmH5diBA1j154wN,22,165582,album,NaN,22,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165.582
438972,Mercedes Carota,3TYOH7ta0101NYssoH5GlU,12,202635,album,NaN,22,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202.635

In [19]:
df1 = df1[['track_name', 'track_id', 'duration_ms', 'album_name', 'release_date','label', 'album_popularity', 'album_id', 'artist_id', 'duration_sec']]

In [20]:
df1

,track_name,track_id,duration_ms,album_name,release_date,label,album_popularity,album_id,artist_id,duration_sec
0,Amazing Grace,6mN8nzCXWUeT5LWEcG1Utx,555521,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,6,3VoHMFQzFr9v163HXRvfo2,002nyxOMwdc9EgNEo7ETcF,555.521
1,Silent Night,58sgjtx3FOnBBEOd3BQE6C,535041,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,6,3VoHMFQzFr9v163HXRvfo2,002nyxOMwdc9EgNEo7ETcF,535.041
2,Ancient Canyons,45tQJhm0WSk5VWMZK3FsLK,545855,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,6,3VoHMFQzFr9v163HXRvfo2,002nyxOMwdc9EgNEo7ETcF,545.855
3,Pacha Mama Medicina,3VFD7QqkJSg0OR6yBwKl7A,305241,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,6,3VoHMFQzFr9v163HXRvfo2,002nyxOMwdc9EgNEo7ETcF,305.241
4,Palace Of Light,7LwJV5BEIC9BQnzvaBSyCc,351060,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,6,3VoHMFQzFr9v163HXRvfo2,002nyxOMwdc9EgNEo7ETcF,351.060
...,...,...,...,...,...,...,...,...,...,...
438968,Where She Goes,2sTDlCxmuZCTDKKk9f1qus,231704,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,100,4FftCsAcXXD1nFO9RFUNFO,4q3ewBCX7sLwd24euuV69X,231.704
438969,Europa :(,6vh4S1z08AjGipGAEsV62e,11904,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,100,4FftCsAcXXD1nFO9RFUNFO,4q3ewBCX7sLwd24euuV69X,11.904
438970,Seda,1YnChEM51BVZ5dRhbVFEMl,190476,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,100,4FftCsAcXXD1nFO9RFUNFO,4q3ewBCX7sLwd24euuV69X,190.476
438971,Un Preview,5ixdmTpCmH5diBA1j154wN,165582,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,100,4FftCsAcXXD1nFO9RFUNFO,4q3ewBCX7sLwd24euuV69X,165.582
438972,Mercedes Carota,3TYOH7ta0101NYssoH5GlU,202635,Nadie Sabe Lo Que Va A Pasar Mañana,2023-10-13 00:00:00 UTC,Rimas Entertainment LLC,100,4FftCsAcXXD1nFO9RFUNFO,4q3ewBCX7sLwd24euuV69X,202.635

In [52]:
df1.isna().sum()

track_name           2
track_id             0
duration_ms          0
album_name           0
release_date        23
label               24
album_popularity     0
album_id             0
artist_id            0
duration_sec         0
dtype: int64

In [22]:
df1.to_csv('Albums_cleaned.csv')

In [24]:
df2 = pd.read_csv('spotify_artist_data_2023.csv')

In [25]:
df2

,id,name,artist_popularity,artist_genres,followers,genre_0,genre_1,genre_2,genre_3,genre_4,genre_5,genre_6
0,6GkSLJj5CGLIckLIb8J4LR,Late Night Fights,0,['minneapolis punk'],184,minneapolis punk,NaN,NaN,NaN,NaN,NaN,NaN
1,1N0VwQy5PRJymrRvlRzDIj,Sub Par All Star,0,['antiviral pop'],491,antiviral pop,NaN,NaN,NaN,NaN,NaN,NaN
2,4Ch4BIKKwMJsiu1oVLDwpX,Nirvana Meditation 8D,0,['8d'],56,8d,NaN,NaN,NaN,NaN,NaN,NaN
3,5h2iINTOvhghVcpIzrztPP,Red Hot Rebellion,0,['action rock'],394,action rock,NaN,NaN,NaN,NaN,NaN,NaN
4,7dE2MLL2SaI6MujpU5HFVi,Nirvana Tribute Band,0,['tribute'],230,tribute,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
37007,12GqGscKJx3aE4t07u7eVZ,Peso Pluma,90,"['corridos tumbados', 'sad sierreno']",9775920,corridos tumbados,sad sierreno,NaN,NaN,NaN,NaN,NaN
37008,1Xyo4u8uXC1ZmMpatF05PJ,The Weeknd,93,"['canadian contemporary r&b', 'canadian pop', ...",75945958,canadian contemporary r&b,canadian pop,pop,NaN,NaN,NaN,NaN
37009,4q3ewBCX7sLwd24euuV69X,Bad Bunny,95,"['reggaeton', 'trap latino', 'urbano latino']",77931484,reggaeton,trap latino,urbano latino,NaN,NaN,NaN,NaN
37010,3TVXtAsR1Inumwj472S9r4,Drake,95,"['canadian hip hop', 'canadian pop', 'hip hop'...",83298497,canadian hip hop,canadian pop,hip hop,pop rap,rap,NaN,NaN
37011,06HL4z0CvFAxyc27GXpf02,Taylor Swift,100,['pop'],95859165,pop,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df2.isna().sum()

id                       0
name                     0
artist_popularity        0
artist_genres            0
followers                0
genre_0              26065
genre_1              32192
genre_2              34572
genre_3              35647
genre_4              36294
genre_5              37012
genre_6              37012
dtype: int64

In [31]:
df2 = df2[['id', 'name', 'artist_popularity', 'followers', 'genre_0']]

In [32]:
df2

,id,name,artist_popularity,followers,genre_0
0,6GkSLJj5CGLIckLIb8J4LR,Late Night Fights,0,184,minneapolis punk
1,1N0VwQy5PRJymrRvlRzDIj,Sub Par All Star,0,491,antiviral pop
2,4Ch4BIKKwMJsiu1oVLDwpX,Nirvana Meditation 8D,0,56,8d
3,5h2iINTOvhghVcpIzrztPP,Red Hot Rebellion,0,394,action rock
4,7dE2MLL2SaI6MujpU5HFVi,Nirvana Tribute Band,0,230,tribute
...,...,...,...,...,...
37007,12GqGscKJx3aE4t07u7eVZ,Peso Pluma,90,9775920,corridos tumbados
37008,1Xyo4u8uXC1ZmMpatF05PJ,The Weeknd,93,75945958,canadian contemporary r&b
37009,4q3ewBCX7sLwd24euuV69X,Bad Bunny,95,77931484,reggaeton
37010,3TVXtAsR1Inumwj472S9r4,Drake,95,83298497,canadian hip hop
37011,06HL4z0CvFAxyc27GXpf02,Taylor Swift,100,95859165,pop

In [33]:
df2.columns = ['id', 'artist_name', 'artist_popularity','followers','genre']

In [34]:
df2

,id,artist_name,artist_popularity,followers,genre
0,6GkSLJj5CGLIckLIb8J4LR,Late Night Fights,0,184,minneapolis punk
1,1N0VwQy5PRJymrRvlRzDIj,Sub Par All Star,0,491,antiviral pop
2,4Ch4BIKKwMJsiu1oVLDwpX,Nirvana Meditation 8D,0,56,8d
3,5h2iINTOvhghVcpIzrztPP,Red Hot Rebellion,0,394,action rock
4,7dE2MLL2SaI6MujpU5HFVi,Nirvana Tribute Band,0,230,tribute
...,...,...,...,...,...
37007,12GqGscKJx3aE4t07u7eVZ,Peso Pluma,90,9775920,corridos tumbados
37008,1Xyo4u8uXC1ZmMpatF05PJ,The Weeknd,93,75945958,canadian contemporary r&b
37009,4q3ewBCX7sLwd24euuV69X,Bad Bunny,95,77931484,reggaeton
37010,3TVXtAsR1Inumwj472S9r4,Drake,95,83298497,canadian hip hop
37011,06HL4z0CvFAxyc27GXpf02,Taylor Swift,100,95859165,pop

In [36]:
df2.to_csv('Artists_cleaned.csv')

In [43]:
df3 = pd.read_csv('spotify_tracks_data_2023.csv')

In [44]:
df3

                            id  track_popularity  explicit
0       02MBhqgR7WeeI4ZfB6Lo0i                 0     False
1       5j4M4gLYuUy9PVw0vsXWyq                 0     False
2       46EucLPJpx0QM3SCjzzdP0                 0     False
3       4nK2LvW3osgDT89S38Mcg6                 0     False
4       1Pq37WIQZDG7yNFnY5IbqG                 0     False
...                        ...               ...       ...
438933  4rXLjWdF2ZZpXCVTfWcshS                93      True
438934  7MXVkk9YMctZqd1Srtv4MB                94      True
438935  6uIIdjYTxxpWOyWuVXrKQO                95      True
438936  4MjDJD8cW7iVeWInc2Bdyj                96      True
438937  7iQXYTyuG13aoeHxGG28Nh                97      True

[438938 rows x 3 columns]

In [47]:
df3 = df3[['id', 'track_popularity']]

In [48]:
df3

                            id  track_popularity
0       02MBhqgR7WeeI4ZfB6Lo0i                 0
1       5j4M4gLYuUy9PVw0vsXWyq                 0
2       46EucLPJpx0QM3SCjzzdP0                 0
3       4nK2LvW3osgDT89S38Mcg6                 0
4       1Pq37WIQZDG7yNFnY5IbqG                 0
...                        ...               ...
438933  4rXLjWdF2ZZpXCVTfWcshS                93
438934  7MXVkk9YMctZqd1Srtv4MB                94
438935  6uIIdjYTxxpWOyWuVXrKQO                95
438936  4MjDJD8cW7iVeWInc2Bdyj                96
438937  7iQXYTyuG13aoeHxGG28Nh                97

[438938 rows x 2 columns]

In [49]:
df3.columns= ['track_id', 'track_popularity']

In [50]:
df3

                      track_id  track_popularity
0       02MBhqgR7WeeI4ZfB6Lo0i                 0
1       5j4M4gLYuUy9PVw0vsXWyq                 0
2       46EucLPJpx0QM3SCjzzdP0                 0
3       4nK2LvW3osgDT89S38Mcg6                 0
4       1Pq37WIQZDG7yNFnY5IbqG                 0
...                        ...               ...
438933  4rXLjWdF2ZZpXCVTfWcshS                93
438934  7MXVkk9YMctZqd1Srtv4MB                94
438935  6uIIdjYTxxpWOyWuVXrKQO                95
438936  4MjDJD8cW7iVeWInc2Bdyj                96
438937  7iQXYTyuG13aoeHxGG28Nh                97

[438938 rows x 2 columns]

In [51]:
df3.isna().sum()

track_id            0
track_popularity    0
dtype: int64

In [55]:
df3.to_csv('Tracks_Cleaned.csv')